on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test

publish-artifact:
  runs-on: ubuntu-latest
  needs: [unit-test]
  permissions:
    contents: read
    packages: write
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
    - name: Set up Maven Settings for deploy
      uses: s4u/maven-settings-action@v2.1.1
    - name: Publish packag
      env:
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: mvn source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/SusanaAO/reto-libreria'

        
 